# Generated by Django 4.2.6 on 2023-10-26 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.OneToOneField(limit_choices_to={'type': 'Restaurant Owner'}, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
