# Generated by Django 4.2.6 on 2023-10-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_type_userprofile_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('RESTAURANT_OWNER', 'Restaurant Owner'), ('RESTAURANT_STAFF', 'Restaurant Staff'), ('DELIVERY_AGENT', 'Delivery Agent')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
